---
- block:
    - name: set the repo main url
      set_fact:
        url: "http://us.archive.ubuntu.com/ubuntu/"
        
    - name: This will import the script 
      script: "getrepoinfo.py {{ url }}"
      register: content
    
    - debug:
        msg: "This is the content: {{ content }}"
  rescue:
    - debug:
        msg: "Error Occured During Task: {{ ansible_failed_task.name }} With Error: {{ ansible_failed_result.msg }}"
